AWSTemplateFormatVersion: 2010-09-09
Description: aluramed-api

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  CognitoArn:
    Type: String

Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 100
    MemorySize: 128
    Environment:
        Variables:
          PACIENTES_TABLE: !Ref PacientesTable

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: aluramed-api
      StageName: Prod
      Cors:
         AllowMethods: "'*'"
         AllowHeaders: "'*'"
         AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref CognitoArn

  listarPacientesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/pacientes.listar  
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PacientesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /pacientes
            Method: GET
            RestApiId:
              Ref: Api
            Auth:
              Authorizer: CognitoAuthorizer

  obterPacienteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/pacientes.obter  
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PacientesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /pacientes/{pacienteId}
            Method: GET
            RestApiId:
              Ref: Api
            Auth:
              Authorizer: CognitoAuthorizer

  cadastrarPacienteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/pacientes.cadastrar  
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PacientesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /pacientes
            Method: POST
            RestApiId:
              Ref: Api
            Auth:
              Authorizer: CognitoAuthorizer

  atualizarPacienteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/pacientes.atualizar  
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PacientesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /pacientes/{pacienteId}
            Method: PUT
            RestApiId:
              Ref: Api
            Auth:
              Authorizer: CognitoAuthorizer

  excluirPacienteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/pacientes.excluir  
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PacientesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /pacientes/{pacienteId}
            Method: DELETE
            RestApiId:
              Ref: Api
            Auth:
              Authorizer: CognitoAuthorizer

  PacientesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PACIENTES_TABLE
      AttributeDefinitions:
        - AttributeName: usuario_id
          AttributeType: S
        - AttributeName: paciente_id
          AttributeType: S
      KeySchema:
        - AttributeName: usuario_id
          KeyType: HASH
        - AttributeName: paciente_id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1  

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
